//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISpan.Inseparable.SqlDataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InseparableEntities : DbContext
    {
        public InseparableEntities()
            : base("name=InseparableEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activities> Activities { get; set; }
        public virtual DbSet<ActivityParticipants> ActivityParticipants { get; set; }
        public virtual DbSet<Administrators> Administrators { get; set; }
        public virtual DbSet<Areas> Areas { get; set; }
        public virtual DbSet<Articles> Articles { get; set; }
        public virtual DbSet<Cinemas> Cinemas { get; set; }
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<Friends> Friends { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<KeywordDetails> KeywordDetails { get; set; }
        public virtual DbSet<Keywords> Keywords { get; set; }
        public virtual DbSet<MemberFavoriteMovieCategories> MemberFavoriteMovieCategories { get; set; }
        public virtual DbSet<MemberPoints> MemberPoints { get; set; }
        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<MovieCategories> MovieCategories { get; set; }
        public virtual DbSet<MovieCategoryDetails> MovieCategoryDetails { get; set; }
        public virtual DbSet<MovieLevels> MovieLevels { get; set; }
        public virtual DbSet<Movies> Movies { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<ProductCategories> ProductCategories { get; set; }
        public virtual DbSet<ProductOrderDetails> ProductOrderDetails { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Rooms> Rooms { get; set; }
        public virtual DbSet<Seats> Seats { get; set; }
        public virtual DbSet<Sessions> Sessions { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TicketOrderDetails> TicketOrderDetails { get; set; }
    }
}
