//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISpan.Inseparable.SqlDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.ProductOrderDetails = new HashSet<ProductOrderDetails>();
            this.TicketOrderDetails = new HashSet<TicketOrderDetails>();
        }
    
        public int OrderID { get; set; }
        public int MemberID { get; set; }
        public int CinemaID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime ModifiedTime { get; set; }
        public int TotalMoney { get; set; }
    
        public virtual Cinemas Cinemas { get; set; }
        public virtual Members Members { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductOrderDetails> ProductOrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketOrderDetails> TicketOrderDetails { get; set; }
    }
}
