//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISpan.Inseparable.SqlDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketOrderDetails
    {
        public int TicketItem_no { get; set; }
        public int OrderID { get; set; }
        public int MovieID { get; set; }
        public int SessionID { get; set; }
        public int SeatID { get; set; }
        public int RoomID { get; set; }
        public int TicketUnitprice { get; set; }
        public decimal TicketDiscount { get; set; }
        public int TicketSubtotal { get; set; }
    
        public virtual Movies Movies { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual Rooms Rooms { get; set; }
        public virtual Seats Seats { get; set; }
        public virtual Sessions Sessions { get; set; }
    }
}
